/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.mAdmin;

import java.awt.BorderLayout;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import sang.ne.ql_mb.Dao.SanBayDao;
import sang.ne.ql_mb.Dao.TuyenBayDao;
import sang.ne.ql_mb.entity.SanBay;
import sang.ne.ql_mb.help.DataValidator;
import sang.ne.ql_mb.help.MessageHelper;

/**
 *
 * @author Yahiko
 */
public class Airport extends javax.swing.JPanel {
    private MainFrameAdmin parentform;
    private DefaultTableModel tblTableModel;
    /**
     * Creates new form Airport;
     */
    public Airport() {
        initComponents();
        initTable();
        LoadDataTable();
    }
    
    public void initTable(){
        tblTableModel = new DefaultTableModel();
        JScrollPane jsp=new JScrollPane();
        table_SanBay.add(jsp,BorderLayout.CENTER);
        tblTableModel.setColumnIdentifiers(new String[]{"Mã Sân Bay","Tên Sân Bay","Tỉnh Thành"});
        table_SanBay.setModel(tblTableModel);
       
    }
    private void LoadDataTable(){
        try {
           SanBayDao sanBay=new SanBayDao();
           List <SanBay> list=sanBay.FindAllSanBay();
           tblTableModel.setRowCount(0);
           for(SanBay sb :list){
               tblTableModel.addRow(new Object[]{
                   sb.getMaSanBay(),sb.getTenSanBay(),sb.getTinhThanh()
               });
           }
           tblTableModel.fireTableDataChanged();
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_MaSanBay = new javax.swing.JTextField();
        txt_TenSanBay = new javax.swing.JTextField();
        btn_New = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_SanBay = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txt_TinhThanh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_layma = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(950, 956));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Airport/Id.png"))); // NOI18N
        jLabel1.setText("Mã Sân Bay");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Airport/airport.png"))); // NOI18N
        jLabel2.setText("Tên Sân Bay");

        btn_New.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_New.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/new.png"))); // NOI18N
        btn_New.setText("Tạo Mới");
        btn_New.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewActionPerformed(evt);
            }
        });

        btn_Update.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/edit.png"))); // NOI18N
        btn_Update.setText("Cập Nhật");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_Save.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        btn_Save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/add.png"))); // NOI18N
        btn_Save.setText("Thêm");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        table_SanBay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Sân Bay", "Tên Sân Bay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_SanBay.setAutoscrolls(false);
        table_SanBay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_SanBayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_SanBay);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Airport/Country.png"))); // NOI18N
        jLabel3.setText("Tỉnh Thành");

        jLabel4.setBackground(new java.awt.Color(0, 51, 51));
        jLabel4.setForeground(new java.awt.Color(153, 153, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Airport/1.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Airport/1.jpg"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Airport/3.jpg"))); // NOI18N

        btn_layma.setText("Lấy Mã");
        btn_layma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laymaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_MaSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btn_layma))
                            .addComponent(txt_TinhThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_New)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Update))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_layma))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TenSanBay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_TinhThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_New, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
       StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(txt_MaSanBay, sb, "Mã Sân Bay Không Được Để Trống ");
        DataValidator.validateEmpty(txt_TenSanBay, sb, "Tên Sân Bay Không Được Để Trống ");
        DataValidator.validateEmpty(txt_TinhThanh, sb, "Tên Tỉnh Thành Không Được Để Trống ");
        
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentform, sb.toString(), "ERROR");
            return;
        }
        try {
            SanBay sanbay=new SanBay();
            sanbay.setMaSanBay(txt_MaSanBay.getText());
            sanbay.setTenSanBay(txt_TenSanBay.getText());
            sanbay.setTinhThanh(txt_TinhThanh.getText());
            SanBayDao dao=new SanBayDao();
            if (dao.Insert(sanbay)==true)
            {
                 MessageHelper.showConfirmMesage(parentform, "Đã Lưu", "Thông báo");
                 LoadDataTable();
            }     
            else 
            {
                MessageHelper.ErrorMesage(parentform, "Không Lưu Được Do Lỗi ", "Cảnh Báo");
            }
        }catch (Exception e) {
             e.printStackTrace();
            MessageHelper.ErrorMesage(parentform,e.getMessage(),"ERROR");
        }
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
         StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(txt_MaSanBay, sb, "Mã Sân Bay Không Được Để Trống ");
        DataValidator.validateEmpty(txt_TenSanBay, sb, "Tên Sân Bay Không Được Để Trống ");
        DataValidator.validateEmpty(txt_TinhThanh, sb, "Tên Tỉnh Thành Không Được Để Trống ");
        
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentform, sb.toString(), "ERROR");
            return;
        }
        if (MessageHelper.showConfirmMesage(parentform, "Bạn Có muốn cập nhật không ","Thông Báo") 
                == JOptionPane.NO_OPTION)
        {
            return;
        }
        try {
            SanBay sanbay=new SanBay();
            sanbay.setMaSanBay(txt_MaSanBay.getText());
            sanbay.setTenSanBay(txt_TenSanBay.getText());
            sanbay.setTinhThanh(txt_TinhThanh.getText());
            SanBayDao dao=new SanBayDao();
            if (dao.Update(sanbay)==true)
            {
                 MessageHelper.showConfirmMesage(parentform, "Đã Cập Nhật", "Thông báo");
                 LoadDataTable();
            }     
            else 
            {
                MessageHelper.ErrorMesage(parentform, "Không Cập Nhật Được ", "Cảnh Báo");
            }
        }catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentform,e.getMessage(),"ERROR"); 
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(txt_MaSanBay, sb, "Mã Sân Bay Không Được Để Trống ");
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentform, sb.toString(), "ERROR");
            return;
        }
        if (MessageHelper.showConfirmMesage(parentform, "Bạn Có muốn Xóa không ","Thông Báo") 
                == JOptionPane.NO_OPTION)
        {
            return;
        }
        try {
            SanBay sanBay=new SanBay();
            sanBay.setMaSanBay(txt_MaSanBay.getText());
            SanBayDao dao=new SanBayDao();
            if (dao.Delete(sanBay)==true)
            {
                MessageHelper.ErrorMesage(parentform, "Đã Xóa ", "Cảnh Báo");
                 LoadDataTable();
            }     
            else 
            {
                MessageHelper.showConfirmMesage(parentform, "Không Xóa Được", "Thông báo");
            }
        }catch (Exception e) {
             e.printStackTrace();
            MessageHelper.ErrorMesage(parentform,e.getMessage(),"ERROR");
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_NewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewActionPerformed
        txt_MaSanBay.setText("");
        txt_TenSanBay.setText("");
        txt_TinhThanh.setText("");
        LoadDataTable();
    }//GEN-LAST:event_btn_NewActionPerformed

    private void table_SanBayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_SanBayMouseClicked
        try {
            int row=table_SanBay.getSelectedRow();
            if (row>=0) 
            {
                String id=(String) tblTableModel.getValueAt(row,0);
                SanBayDao sb=new SanBayDao();
                SanBay sanBay=sb.FindSanBay(id);
                if (sanBay!=null) {
                    txt_MaSanBay.setText(sanBay.getMaSanBay());
                    txt_TenSanBay.setText(sanBay.getTenSanBay());
                    txt_TinhThanh.setText(sanBay.getTinhThanh());
               }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentform,"Lỗi","Lỗi");
        }
    }//GEN-LAST:event_table_SanBayMouseClicked

    private void btn_laymaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laymaActionPerformed
        try {
            String giatri;
            SanBayDao tb=new SanBayDao();
            Random random=new Random();
            do 
            {
                giatri="";
                int value=random.nextInt(100)+ 1;
                if (value<10)
                {
                    giatri="VN_0"+ String.valueOf(value);
                }  
                else
                {
                    giatri="VN_"+ String.valueOf(value);
                }       
            }   while(tb.FindSanBay(giatri)!=null) ;
            txt_MaSanBay.setText(giatri);
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_btn_laymaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_New;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_layma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_SanBay;
    private javax.swing.JTextField txt_MaSanBay;
    private javax.swing.JTextField txt_TenSanBay;
    private javax.swing.JTextField txt_TinhThanh;
    // End of variables declaration//GEN-END:variables
}
