/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.mAdmin;

import java.awt.BorderLayout;
import java.util.Date;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import sang.ne.ql_mb.Dao.ChuyenBayDao;
import sang.ne.ql_mb.Dao.PhieuDatChoDao;
import sang.ne.ql_mb.Dao.TuyenBayDao;
import sang.ne.ql_mb.entity.ChuyenBay;
import sang.ne.ql_mb.entity.PhieuDatCho;
import sang.ne.ql_mb.entity.TuyenBay;

/**
 *
 * @author Yahiko
 */
public class ChiTiet_hoadon extends javax.swing.JFrame {
    private DefaultTableModel mdDefaultTableModel;
    private MainFrameAdmin parentForm; 
    String s1;
    String s2;
    int dem=0;
    int tongtien=0;
    /**
     * Creates new form ChiTiet_hoadon
     */
    public ChiTiet_hoadon() {
        initComponents();
        this.setTitle("Chi Tiết Phiếu Đặt Chỗ");
        initTable();
        LoadTable(s1,s2);
    }
    public ChiTiet_hoadon(String CMND,String Ngay) {
        initComponents();
        s1=CMND;
        s2=Ngay;
        initTable();
        LoadTable(s1,s2);
        txt_sove.setText(String.valueOf(dem));
        txt_tongtien.setText(String.valueOf(tongtien));
        setLocationRelativeTo(this);
    }
    public void initTable(){
       mdDefaultTableModel = new DefaultTableModel();
       JScrollPane jsp=new JScrollPane();
       table_chitiet.add(jsp,BorderLayout.CENTER);
       mdDefaultTableModel.setColumnIdentifiers(new String[]{"Mã Phiếu","Ngày Đặt","CMND",
                                        "Số Ghế","Nơi Đi","Điểm Đến","Giờ Khởi Hành","Giá Vé"});
       table_chitiet.setModel(mdDefaultTableModel); 
    }
     public void LoadTable(String s, String ss){
         try {
            dem=0;
            tongtien=0;
            PhieuDatChoDao phieu=new PhieuDatChoDao();
            List <PhieuDatCho> list=phieu.findChitietPhieuDatCho(s,ss);
            mdDefaultTableModel.setRowCount(0);
           for(PhieuDatCho sb :list)
           {
               dem++;
               ChuyenBayDao CB=new ChuyenBayDao();
               ChuyenBay sb1=CB.findHoaDonChuyenBay(sb.getMaChuyenBay());
               TuyenBayDao TB=new TuyenBayDao();
               TuyenBay sb2=TB.findHoaDonTuyenBay(sb1.getMaTuyenBay());
               mdDefaultTableModel.addRow(new Object[]{
                   sb.getMaPhieu(),sb.getNgayDat(),sb.getCMND(),sb.getSoGhe(),sb2.getSanBayDi(),sb2.getSanBayDen()
                       ,sb1.getThoiGianBay(),sb.getTongTien()});
               tongtien=tongtien+sb.getTongTien();
               mdDefaultTableModel.fireTableDataChanged();
           }
               
        } catch (Exception e) {
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_chitiet = new javax.swing.JTable();
        btn_close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sove = new javax.swing.JTextField();
        txt_tongtien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table_chitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_chitiet);

        btn_close.setText("Đóng");
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        jLabel1.setText("Số Vé :");

        jLabel2.setText("Tổng Tiền :");

        jLabel3.setText("VND");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txt_sove, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(154, 154, 154)
                        .addComponent(jLabel2)
                        .addGap(28, 28, 28)
                        .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(txt_sove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(6, 6, 6)
                .addComponent(btn_close)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTiet_hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTiet_hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTiet_hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTiet_hoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTiet_hoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_chitiet;
    private javax.swing.JTextField txt_sove;
    private javax.swing.JTextField txt_tongtien;
    // End of variables declaration//GEN-END:variables
}
