/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.mAdmin;

import java.awt.event.MouseListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;
import sang.ne.ql_mb.entity.KhachHang;
import sang.ne.ql_mb.mMainFrame.Login;

/**
 *
 * @author Yahiko
 */
public class MainFrameAdmin extends javax.swing.JFrame {
    private Customer_Manager mCustomer_Manager;
    private QL_HoaDon mBill_Manager;
    private AboutUs mAboutUs;
    private Airport mAirport;
    private Login mLogin;
    private Trip_Manager mTrip_Manager;
    private Home mhome;
    private QL_Tuyenbay tuyenbay;
    private ThongKe_HD thongke_hd;
    private changePass changePass;
    int index=0;
    String User;
  
    /**
     * Creates new form MainFrame
     */
    public MainFrameAdmin() {
        this.setTitle("Phần Mềm Bán Vé Máy Bay Giá Rẻ");
        initComponents();
        setLocationRelativeTo(null);
        home();
    }

    public MainFrameAdmin(String username) {
        this.setTitle("Phần Mềm Bán Vé Máy Bay Giá Rẻ");
        initComponents();
        setLocationRelativeTo(null);
        this.User=username;
        home();
    }
    public void home(){
        mhome=new Home();
        tbl_Mainboard.addTab("Trang Chủ", mhome);
        tbl_Mainboard.setSelectedComponent(mhome);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        btn_logout = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btn_trangchu = new javax.swing.JButton();
        jSeparator13 = new javax.swing.JToolBar.Separator();
        btn_Customer = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btn_QLSB = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JToolBar.Separator();
        btn_trip = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btn_tuyenbay = new javax.swing.JButton();
        jSeparator10 = new javax.swing.JToolBar.Separator();
        btn_Statitic = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JToolBar.Separator();
        btn_thongke = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JToolBar.Separator();
        btn_About = new javax.swing.JButton();
        tbl_Mainboard = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnu_system = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator16 = new javax.swing.JPopupMenu.Separator();
        mnu_Logout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        menu_exit = new javax.swing.JMenuItem();
        mnu_Quanly = new javax.swing.JMenu();
        mnu_Customer = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnu_trip = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        mnu_SanBay = new javax.swing.JMenuItem();
        mnu_help = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        btn_AboutUs = new javax.swing.JMenuItem();
        mnu_search = new javax.swing.JMenu();
        jmn_hoadon = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        nmu_statitic = new javax.swing.JMenu();
        mnu_Bill = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Bookmark.png"))); // NOI18N
        btn_logout.setText("Đăng Xuất");
        btn_logout.setFocusable(false);
        btn_logout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_logout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_logout);
        jToolBar1.add(jSeparator4);

        btn_trangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Home.png"))); // NOI18N
        btn_trangchu.setText("Trang Chủ");
        btn_trangchu.setFocusable(false);
        btn_trangchu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trangchu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_trangchuActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_trangchu);
        jToolBar1.add(jSeparator13);

        btn_Customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/User.png"))); // NOI18N
        btn_Customer.setText("Quản Lý Khách Hàng");
        btn_Customer.setFocusable(false);
        btn_Customer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Customer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CustomerActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Customer);
        jToolBar1.add(jSeparator7);

        btn_QLSB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Mb.png"))); // NOI18N
        btn_QLSB.setText("    Quản Lý Sân Bay     ");
        btn_QLSB.setFocusable(false);
        btn_QLSB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_QLSB.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_QLSB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QLSBActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_QLSB);
        jToolBar1.add(jSeparator14);

        btn_trip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Temporary.png"))); // NOI18N
        btn_trip.setText("Quản Lý Chuyến Bay");
        btn_trip.setFocusable(false);
        btn_trip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_trip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_trip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tripActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_trip);
        jToolBar1.add(jSeparator8);

        btn_tuyenbay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Char.png"))); // NOI18N
        btn_tuyenbay.setText("Quản Lý Tuyến Bay");
        btn_tuyenbay.setFocusable(false);
        btn_tuyenbay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_tuyenbay.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_tuyenbay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tuyenbayActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_tuyenbay);
        jToolBar1.add(jSeparator10);

        btn_Statitic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/statistic_48.png"))); // NOI18N
        btn_Statitic.setText("Tra Cứu Hóa Đơn");
        btn_Statitic.setFocusable(false);
        btn_Statitic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_Statitic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_Statitic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StatiticActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_Statitic);
        jToolBar1.add(jSeparator9);

        btn_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Stats.png"))); // NOI18N
        btn_thongke.setText("Thống Kê");
        btn_thongke.setFocusable(false);
        btn_thongke.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_thongke.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_thongke);
        jToolBar1.add(jSeparator15);

        btn_About.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Alert.png"))); // NOI18N
        btn_About.setText("      Chi Tiết      ");
        btn_About.setFocusable(false);
        btn_About.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_About.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_About.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AboutActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_About);

        tbl_Mainboard.setBackground(new java.awt.Color(204, 204, 255));
        tbl_Mainboard.setForeground(new java.awt.Color(204, 204, 255));

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(0, 51, 255));

        mnu_system.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnu_system.setText("Hệ Thống");
        mnu_system.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mnu_system.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        mnu_system.setMaximumSize(new java.awt.Dimension(72, 32767));
        mnu_system.setPreferredSize(new java.awt.Dimension(70, 21));

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Đổi Mật Khẩu");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnu_system.add(jMenuItem1);
        mnu_system.add(jSeparator16);

        mnu_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnu_Logout.setText("Đăng Xuất");
        mnu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_LogoutActionPerformed(evt);
            }
        });
        mnu_system.add(mnu_Logout);
        mnu_system.add(jSeparator1);

        menu_exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menu_exit.setText("Thoát");
        menu_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_exitActionPerformed(evt);
            }
        });
        mnu_system.add(menu_exit);

        jMenuBar1.add(mnu_system);

        mnu_Quanly.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnu_Quanly.setText("Quản Lý   ");
        mnu_Quanly.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mnu_Quanly.setMaximumSize(new java.awt.Dimension(70, 32767));
        mnu_Quanly.setMinimumSize(new java.awt.Dimension(70, 21));
        mnu_Quanly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_QuanlyActionPerformed(evt);
            }
        });

        mnu_Customer.setText("Quản Lý Khách Hàng");
        mnu_Customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_CustomerActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mnu_Customer);
        mnu_Quanly.add(jSeparator2);

        mnu_trip.setText("Quản Lý Chuyến Bay");
        mnu_trip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_tripActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mnu_trip);
        mnu_Quanly.add(jSeparator11);

        mnu_SanBay.setText("Quản Lý Sân Bay");
        mnu_SanBay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_SanBayActionPerformed(evt);
            }
        });
        mnu_Quanly.add(mnu_SanBay);

        jMenuBar1.add(mnu_Quanly);

        mnu_help.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnu_help.setText("Trợ Giúp");
        mnu_help.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mnu_help.setPreferredSize(new java.awt.Dimension(70, 21));

        jMenuItem6.setText("Nội Dung");
        mnu_help.add(jMenuItem6);
        mnu_help.add(jSeparator3);

        btn_AboutUs.setText("Giới Thiệu");
        btn_AboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AboutUsActionPerformed(evt);
            }
        });
        mnu_help.add(btn_AboutUs);

        jMenuBar1.add(mnu_help);

        mnu_search.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnu_search.setText("Tra Cứu");
        mnu_search.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        mnu_search.setMaximumSize(new java.awt.Dimension(65, 32767));
        mnu_search.setMinimumSize(new java.awt.Dimension(70, 21));

        jmn_hoadon.setText("Hóa Đơn ");
        jmn_hoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmn_hoadonActionPerformed(evt);
            }
        });
        mnu_search.add(jmn_hoadon);
        mnu_search.add(jSeparator12);

        jMenuBar1.add(mnu_search);

        nmu_statitic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nmu_statitic.setText("Thống Kê");
        nmu_statitic.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        nmu_statitic.setMinimumSize(new java.awt.Dimension(70, 21));
        nmu_statitic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmu_statiticActionPerformed(evt);
            }
        });

        mnu_Bill.setText("Hóa Đơn");
        mnu_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnu_BillActionPerformed(evt);
            }
        });
        nmu_statitic.add(mnu_Bill);

        jMenuBar1.add(nmu_statitic);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_Mainboard, javax.swing.GroupLayout.PREFERRED_SIZE, 1200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbl_Mainboard, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menu_exitActionPerformed

    private void mnu_QuanlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_QuanlyActionPerformed
      
        
    }//GEN-LAST:event_mnu_QuanlyActionPerformed

    private void mnu_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_CustomerActionPerformed
        mCustomer_Manager=new Customer_Manager();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/User12.png"));
        tbl_Mainboard.addTab("Quản lí Khách Hàng ",icon,mCustomer_Manager,"Quản Lí Khách Hàng");
        tbl_Mainboard.remove(index);
        //tbl_Mainboard.addTab("Quản Lý Khách Hàng", mCustomer_Manager);
        tbl_Mainboard.setComponentAt(index , mCustomer_Manager);
        tbl_Mainboard.setSelectedComponent(mCustomer_Manager);
       
    }//GEN-LAST:event_mnu_CustomerActionPerformed

    private void nmu_statiticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmu_statiticActionPerformed
      
    }//GEN-LAST:event_nmu_statiticActionPerformed

    private void btn_StatiticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StatiticActionPerformed
        mBill_Manager=new QL_HoaDon();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/char.png"));
        tbl_Mainboard.addTab("Quản Lý Hóa Đơn",icon,mBill_Manager,"Tra Cứu Hóa Đơn");
        //tbl_Mainboard.add(mBill_Manager);
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mBill_Manager);
        tbl_Mainboard.setSelectedComponent(mBill_Manager);
        
    }//GEN-LAST:event_btn_StatiticActionPerformed

    private void btn_CustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CustomerActionPerformed

        mCustomer_Manager=new Customer_Manager();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/User12.png"));
        tbl_Mainboard.addTab("Quản lí Khách Hàng ",icon,mCustomer_Manager,"Quản Lí Khách Hàng");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mCustomer_Manager);
        tbl_Mainboard.setSelectedComponent(mCustomer_Manager);
    }//GEN-LAST:event_btn_CustomerActionPerformed

    private void btn_tripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tripActionPerformed
      
        mTrip_Manager=new Trip_Manager(); 
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Mb12.png"));
        tbl_Mainboard.addTab("Quản lí Chuyến Bay ",icon,mTrip_Manager,"Quản Lí Chuyến Bay");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mTrip_Manager);
        tbl_Mainboard.setSelectedComponent(mTrip_Manager);                                          
    }//GEN-LAST:event_btn_tripActionPerformed

    private void mnu_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_BillActionPerformed
     
        mBill_Manager=new QL_HoaDon();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/char.png"));
        tbl_Mainboard.addTab("THỐNG KÊ ",icon,mBill_Manager,"THỐNG KÊ");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mBill_Manager);
        tbl_Mainboard.setSelectedComponent(mBill_Manager);
    }//GEN-LAST:event_mnu_BillActionPerformed

    private void btn_AboutUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AboutUsActionPerformed

         {
             mAboutUs=new AboutUs(this,true);
             mAboutUs.setVisible(true);
         }  
    }//GEN-LAST:event_btn_AboutUsActionPerformed

    private void btn_AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AboutActionPerformed
             mAboutUs=new AboutUs(this,true);
             mAboutUs.setVisible(true);                  
    }//GEN-LAST:event_btn_AboutActionPerformed

    private void mnu_SanBayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_SanBayActionPerformed

        mAirport= new Airport();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Mb12.png"));
        tbl_Mainboard.addTab("Quản Lí Sân Bay ",icon,mAirport,"Quản Lí Sân Bay");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index ,mAirport);
        tbl_Mainboard.setSelectedComponent(mAirport);
    }//GEN-LAST:event_mnu_SanBayActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        mLogin=new Login(this, rootPaneCheckingEnabled);
        mLogin.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void mnu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_LogoutActionPerformed
        this.dispose();
        mLogin=new Login(this, rootPaneCheckingEnabled);
        mLogin.setVisible(true);
    }//GEN-LAST:event_mnu_LogoutActionPerformed

    private void btn_QLSBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QLSBActionPerformed
      
        mAirport= new Airport();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Mb12.png"));
        tbl_Mainboard.addTab("Quản Lý Sân Bay ",icon,mAirport,"Quản Lý Sân Bay");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mAirport);
        tbl_Mainboard.setSelectedComponent(mAirport);
    }//GEN-LAST:event_btn_QLSBActionPerformed

    private void mnu_tripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnu_tripActionPerformed
       
        mTrip_Manager=new Trip_Manager(); 
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Mb12.png"));
        tbl_Mainboard.addTab("Quản lí Chuyến Bay ",icon,mTrip_Manager,"Quản Lí Chuyến Bay");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mTrip_Manager);
        tbl_Mainboard.setSelectedComponent(mTrip_Manager);  
    }//GEN-LAST:event_mnu_tripActionPerformed

    private void btn_trangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_trangchuActionPerformed
       this.dispose();
       MainFrameAdmin main=new MainFrameAdmin();
       main.setVisible(true);
    }//GEN-LAST:event_btn_trangchuActionPerformed

    private void btn_tuyenbayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tuyenbayActionPerformed
        tuyenbay=new QL_Tuyenbay();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Mb12.png"));
        tbl_Mainboard.addTab("Quản lí Tuyến Bay ",icon,tuyenbay,"Quản Lí Tuyến Bay");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , tuyenbay);
        tbl_Mainboard.setSelectedComponent(tuyenbay);  
    }//GEN-LAST:event_btn_tuyenbayActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
        thongke_hd=new ThongKe_HD();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/TK12.png"));
        tbl_Mainboard.addTab("Thống Kê",icon,thongke_hd,"Thống Kê");
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index, thongke_hd);
        tbl_Mainboard.setSelectedComponent(thongke_hd);
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jmn_hoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmn_hoadonActionPerformed
        mBill_Manager=new QL_HoaDon();
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/char.png"));
        tbl_Mainboard.addTab("Quản Lý Hóa Đơn",icon,mBill_Manager,"Tra Cứu Hóa Đơn");
        //tbl_Mainboard.add(mBill_Manager);
        tbl_Mainboard.remove(index);
        tbl_Mainboard.setComponentAt(index , mBill_Manager);
        tbl_Mainboard.setSelectedComponent(mBill_Manager);
    }//GEN-LAST:event_jmn_hoadonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        try {
            changePass=new changePass(User);
        } catch (Exception ex) {
            Logger.getLogger(MainFrameAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        changePass.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_About;
    private javax.swing.JMenuItem btn_AboutUs;
    private javax.swing.JButton btn_Customer;
    private javax.swing.JButton btn_QLSB;
    private javax.swing.JButton btn_Statitic;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JButton btn_trangchu;
    private javax.swing.JButton btn_trip;
    private javax.swing.JButton btn_tuyenbay;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JToolBar.Separator jSeparator13;
    private javax.swing.JToolBar.Separator jSeparator14;
    private javax.swing.JToolBar.Separator jSeparator15;
    private javax.swing.JPopupMenu.Separator jSeparator16;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar.Separator jSeparator9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem jmn_hoadon;
    private javax.swing.JMenuItem menu_exit;
    private javax.swing.JMenuItem mnu_Bill;
    private javax.swing.JMenuItem mnu_Customer;
    private javax.swing.JMenuItem mnu_Logout;
    private javax.swing.JMenu mnu_Quanly;
    private javax.swing.JMenuItem mnu_SanBay;
    private javax.swing.JMenu mnu_help;
    private javax.swing.JMenu mnu_search;
    private javax.swing.JMenu mnu_system;
    private javax.swing.JMenuItem mnu_trip;
    private javax.swing.JMenu nmu_statitic;
    private javax.swing.JTabbedPane tbl_Mainboard;
    // End of variables declaration//GEN-END:variables
}
