/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.mAdmin;

import java.awt.BorderLayout;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Formatter;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import sang.ne.ql_mb.Dao.HoaDonDao;
import sang.ne.ql_mb.Dao.KhachHangDao;
import sang.ne.ql_mb.entity.HoaDon;
import sang.ne.ql_mb.entity.KhachHang;
import sang.ne.ql_mb.help.MessageHelper;

/**
 *
 * @author Yahiko
 */
public class QL_HoaDon extends javax.swing.JPanel {
    private DefaultTableModel tblTableModel;
    private MainFrameAdmin parentForm; 
    private ChiTiet_hoadon chitiethd;
    String a;
    Date Ngay;
    SimpleDateFormat stf= new SimpleDateFormat("yyyy-MM-dd");
    /**
     * Creates new form Statitics
     */
    public QL_HoaDon() {
        initComponents();
        initTable();
        LoadTable();
    }
    public void initTable(){
        tblTableModel = new DefaultTableModel();
        JScrollPane jsp=new JScrollPane();
        table_Bill.add(jsp,BorderLayout.CENTER);
        tblTableModel.setColumnIdentifiers(new String[]{"Mã HD","CMND","Họ Và Tên","Số Điện Thoại"
                ,"Giới Tính","Ngày Lập"});
        table_Bill.setModel(tblTableModel);
    }
    public void LoadTable(){
        try {
            HoaDonDao HD=new HoaDonDao();
            KhachHangDao KH=new KhachHangDao();
            List<HoaDon> list=HD.findallHoaDon();
            tblTableModel.setRowCount(0);
           for(HoaDon sb :list)
           {
               String gioitinh="";
               KhachHang KH1=KH.FindKhachHang(sb.getCMND());
               if (KH1.getGIOITINH()==1) gioitinh="Nam";
                       else gioitinh="Nữ";
               tblTableModel.addRow(new Object[]{
                   sb.getMaHD(),sb.getCMND(),KH1.getTENKH(),KH1.getSDT(),gioitinh,sb.getNgayLap()});
           tblTableModel.fireTableDataChanged(); }
           }
        catch (Exception e) {
        }
    }
     public void LoadTable3(Date Ngay){
        try {
            HoaDonDao HD=new HoaDonDao();
            KhachHangDao KH=new KhachHangDao();
            List<HoaDon> list=HD.findallHoaDon();
            tblTableModel.setRowCount(0);
            String date1=stf.format(Ngay);
           for(HoaDon sb :list)
           {
               String date2=stf.format(sb.getNgayLap());
               if (date1.equals(date2))
                {       
                    String gioitinh="";
                    KhachHang KH1=KH.FindKhachHang(sb.getCMND());
                    if (KH1.getGIOITINH()==1) gioitinh="Nam";
                       else gioitinh="Nữ";
                    tblTableModel.addRow(new Object[]{
                    sb.getMaHD(),sb.getCMND(),KH1.getTENKH(),KH1.getSDT(),gioitinh,sb.getNgayLap()});
                }
                tblTableModel.fireTableDataChanged(); }
           }
        catch (Exception e) {
        }
    }
    public void LoadTable2(String CMND){
        try {
            HoaDonDao HD=new HoaDonDao();
            KhachHangDao KH=new KhachHangDao();
            List<HoaDon> list=HD.findallHoaDon();
            tblTableModel.setRowCount(0);
           for(HoaDon sb :list)
            if (sb.getCMND().equals(CMND))
           {
               String gioitinh="";
               KhachHang KH1=KH.FindKhachHang(sb.getCMND());
               if (KH1.getGIOITINH()==1) gioitinh="Nam";
                       else gioitinh="Nữ";
               tblTableModel.addRow(new Object[]{
                   sb.getMaHD(),sb.getCMND(),KH1.getTENKH(),KH1.getSDT(),gioitinh,sb.getNgayLap()});
           tblTableModel.fireTableDataChanged(); }
           }
        catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_chitiethd = new javax.swing.JButton();
        txt_cmnd = new javax.swing.JTextField();
        txt_hoten = new javax.swing.JTextField();
        txt_sdt = new javax.swing.JTextField();
        txt_gioitinh = new javax.swing.JTextField();
        txt_mahd = new javax.swing.JTextField();
        txt_ngaydatve = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Bill = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_tk_cmnd = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_new = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txt_ngaylap = new com.toedter.calendar.JDateChooser();
        btn_tk = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/id-card.png"))); // NOI18N
        jLabel4.setText("CMND");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/user-data_32.png"))); // NOI18N
        jLabel5.setText("Họ Và Tên");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/phone.png"))); // NOI18N
        jLabel6.setText("SĐT");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/male-female.png"))); // NOI18N
        jLabel7.setText("Giới Tính");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/id_bill.png"))); // NOI18N
        jLabel1.setText("Mã Hóa Đơn");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/date.png"))); // NOI18N
        jLabel3.setText("Ngày Đặt Vé");

        btn_chitiethd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btn_chitiethd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/view_detail.png"))); // NOI18N
        btn_chitiethd.setText("Chi Tiết Hóa Đơn ");
        btn_chitiethd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chitiethdActionPerformed(evt);
            }
        });

        table_Bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_Bill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_BillMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Bill);

        jLabel2.setText("CMND");

        btn_search.setText("Tìm Kiếm");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        btn_new.setText("Làm Mới");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        jLabel8.setText("Ngày Lập");

        txt_ngaylap.setDateFormatString("dd-MM-yyyy");

        btn_tk.setText("Tìm Kiếm");
        btn_tk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_sdt, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txt_gioitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txt_mahd, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(txt_ngaydatve)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(95, 95, 95)
                                    .addComponent(txt_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btn_chitiethd)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_new)
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_ngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tk_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_search)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txt_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tk_cmnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search)
                            .addComponent(btn_tk)
                            .addComponent(txt_ngaylap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txt_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_sdt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_mahd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txt_ngaydatve, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btn_chitiethd, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_chitiethdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chitiethdActionPerformed
        String s1=txt_cmnd.getText();
        String s2=txt_ngaydatve.getText();
        chitiethd=new ChiTiet_hoadon(s1,s2);
        chitiethd.setVisible(true);
    }//GEN-LAST:event_btn_chitiethdActionPerformed

    private void table_BillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_BillMouseClicked
        try {
            int row=table_Bill.getSelectedRow();
            if (row>=0)
            {
                String id=(String) tblTableModel.getValueAt(row,0);
                HoaDonDao sb=new HoaDonDao();
                HoaDon hd =sb.FindHoaDon(id);
                KhachHangDao KH=new KhachHangDao();
                KhachHang kh1=KH.FindKhachHang(hd.getCMND());
                if (hd!=null) {
                    txt_cmnd.setText(hd.getCMND());
                    txt_mahd.setText(hd.getMaHD());
                    Format formatter = new SimpleDateFormat("yyyy-MM-dd");
                    String s = formatter.format(hd.getNgayLap());
                    txt_ngaydatve.setText(s);
                    txt_hoten.setText(kh1.getTENKH());
                    txt_sdt.setText(kh1.getSDT());
                    if (kh1.getGIOITINH()==1)
                    {
                        txt_gioitinh.setText("Nam");
                    }
                    else txt_gioitinh.setText("Nữ");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,"Lỗi","Lỗi");
        }
    }//GEN-LAST:event_table_BillMouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        a=txt_tk_cmnd.getText().toString();
        LoadTable2(a);
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        LoadTable();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_tkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tkActionPerformed
        Ngay=txt_ngaylap.getDate();
        LoadTable3(Ngay);
    }//GEN-LAST:event_btn_tkActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_chitiethd;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_tk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable table_Bill;
    private javax.swing.JTextField txt_cmnd;
    private javax.swing.JTextField txt_gioitinh;
    private javax.swing.JTextField txt_hoten;
    private javax.swing.JTextField txt_mahd;
    private javax.swing.JTextField txt_ngaydatve;
    private com.toedter.calendar.JDateChooser txt_ngaylap;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tk_cmnd;
    // End of variables declaration//GEN-END:variables
}
