/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.mAdmin;

import java.awt.BorderLayout;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import sang.ne.ql_mb.Dao.KhachHangDao;
import sang.ne.ql_mb.Dao.SanBayDao;
import sang.ne.ql_mb.Dao.TuyenBayDao;
import sang.ne.ql_mb.entity.KhachHang;
import sang.ne.ql_mb.entity.SanBay;
import sang.ne.ql_mb.entity.TuyenBay;
import sang.ne.ql_mb.help.DataValidator;
import sang.ne.ql_mb.help.MessageHelper;

/**
 *
 * @author Yahiko
 */
public class QL_Tuyenbay extends javax.swing.JPanel {
     private DefaultTableModel tblTableModel;
      private MainFrameAdmin parentForm; 
       String[] arr=new String[100];
       int i;
    
     /**
     * Creates new form tuyenbay
     */
    public QL_Tuyenbay() {
        initComponents();
        inittable();
        loadData();
        cb_noikhoihanh.removeAllItems();
        cb_diemden.removeAllItems();
        i=0;
        try {
           
            SanBayDao sanbay = new SanBayDao();
            List< SanBay > list = sanbay.FindAllSanBay();
            for (SanBay cb : list){
               arr[i]=cb.getTinhThanh(); 
               i++;
               }             
         } catch (Exception e) {
         }
          for (int j = 0; j<i; j++) {
                    cb_noikhoihanh.addItem(arr[j]);
                    cb_diemden.addItem(arr[j]);
             }   
        //loadcbbox();
    }
    public void inittable(){
        tblTableModel=new DefaultTableModel();
        JScrollPane pane=new JScrollPane();
        table_tuyenbay.add(pane,BorderLayout.CENTER);
        tblTableModel.setColumnIdentifiers(new String[]{"Mã Tuyến Bay","Nơi Khởi Hành","Sân Bay Đi","Điểm Đến","Sân Bay Đến","Chiều Dài (Km)"});
        table_tuyenbay.setModel(tblTableModel);
    }
    public void loadData(){
        try{
            TuyenBayDao tuyenbay = new TuyenBayDao();
            SanBayDao sanbay=new SanBayDao();
            List<TuyenBay> list = tuyenbay.findalltuyenBay();
            tblTableModel.setRowCount(0);
            for (TuyenBay cb : list){
               SanBay sb1=sanbay.FindTenSanBay(cb.getSanBayDi());
               SanBay sb2=sanbay.FindTenSanBay(cb.getSanBayDen());
               tblTableModel.addRow(new Object[]{
               cb.getMaTuyenBay(),cb.getSanBayDi(),sb1.getTenSanBay(),cb.getSanBayDen(),sb2.getTenSanBay(),cb.getChieudai()
               });
                
            }
            
            tblTableModel.fireTableDataChanged();
            
        } catch (Exception e) {
            
        }
    }
    private void loadcbbox(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_tuyenbay = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_matuyenbay = new javax.swing.JTextField();
        txt_noikhoihanh = new javax.swing.JTextField();
        txt_diemden = new javax.swing.JTextField();
        txt_chieudai = new javax.swing.JTextField();
        btn_new = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        cb_noikhoihanh = new javax.swing.JComboBox<>();
        cb_diemden = new javax.swing.JComboBox<>();
        btn_layma = new javax.swing.JButton();

        table_tuyenbay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_tuyenbay.setAutoscrolls(false);
        table_tuyenbay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_tuyenbayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_tuyenbay);
        table_tuyenbay.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/travel.png"))); // NOI18N
        jLabel1.setText("Mã Tuyến Bay");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/start-up.png"))); // NOI18N
        jLabel2.setText("Nơi Khởi Hành");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/destination.png"))); // NOI18N
        jLabel3.setText("Điểm Đến");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/length.png"))); // NOI18N
        jLabel4.setText("Chiều Dài ( Km )");

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/new.png"))); // NOI18N
        btn_new.setText("Làm Mới");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/add.png"))); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/edit.png"))); // NOI18N
        btn_update.setText("Cập Nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        cb_noikhoihanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_noikhoihanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_noikhoihanhActionPerformed(evt);
            }
        });

        cb_diemden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_diemden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_diemdenActionPerformed(evt);
            }
        });

        btn_layma.setText("Lấy Mã");
        btn_layma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laymaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(67, 67, 67))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txt_noikhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_chieudai, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_matuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_diemden, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_noikhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_diemden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_new, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_layma)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_matuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(btn_layma))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_noikhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_noikhoihanh, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_new, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_update, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_diemden, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(txt_diemden, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_chieudai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cb_noikhoihanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_noikhoihanhActionPerformed
         if (cb_noikhoihanh.getSelectedItem()!=null) {
            txt_noikhoihanh.setText(cb_noikhoihanh.getSelectedItem().toString());
        }
        else 
            txt_noikhoihanh.setText(cb_noikhoihanh.getItemAt(1));
    }//GEN-LAST:event_cb_noikhoihanhActionPerformed

    private void cb_diemdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_diemdenActionPerformed
         if (cb_diemden.getSelectedItem()!=null) {
            txt_diemden.setText(cb_diemden.getSelectedItem().toString());
        }
        else 
            txt_diemden.setText(cb_diemden.getItemAt(1));
    }//GEN-LAST:event_cb_diemdenActionPerformed

    private void table_tuyenbayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tuyenbayMouseClicked
        try {
            int row=table_tuyenbay.getSelectedRow();
            if (row>=0) 
            {
                String id=(String) tblTableModel.getValueAt(row,0);
                TuyenBayDao sb=new TuyenBayDao();
                TuyenBay tuyenb =sb.findTuyenBay(id);
                if (tuyenb!=null) {
                    txt_matuyenbay.setText(tuyenb.getMaTuyenBay());
                    txt_noikhoihanh.setText(tuyenb.getSanBayDi());
                    txt_diemden.setText(tuyenb.getSanBayDen());
                    int x=tuyenb.getChieudai();
                    txt_chieudai.setText(String.valueOf(x));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
             MessageHelper.ErrorMesage(parentForm,"Lỗi","Lỗi");
        }
    }//GEN-LAST:event_table_tuyenbayMouseClicked

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        txt_chieudai.setText("");
        txt_diemden.setText("");
        txt_matuyenbay.setText("");
        txt_noikhoihanh.setText("");
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_laymaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laymaActionPerformed
        
        try {
            String giatri;
            TuyenBayDao tb=new TuyenBayDao();
            Random random=new Random();
            do 
            {
                giatri="";
                int value=random.nextInt(100)+ 1;
                if (value<10)
                {
                    giatri="N0"+ String.valueOf(value);
                }  
                else
                {
                    giatri="N"+ String.valueOf(value);
                }       
            }   while(tb.findTuyenBay(giatri)!=null) ;
            txt_matuyenbay.setText(giatri);
        } catch (Exception e) {
        }
       
    }//GEN-LAST:event_btn_laymaActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(txt_matuyenbay, sb, "Mã Tuyến Bay không được để trống");
        DataValidator.validateEmpty(txt_noikhoihanh, sb, "Nơi Khởi Hành không được để trống");
        DataValidator.validateEmpty(txt_diemden, sb, "Điểm Đến không được để trống");
        DataValidator.validateEmpty(txt_chieudai, sb, "Chiều Dài không được để trống");
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentForm, sb.toString(), "LỖI");
            return;
        }
        String s1=txt_noikhoihanh.getText();
        String s2=txt_diemden.getText();
        if (s1.equals(s2)) {
           MessageHelper.ErrorMesage(this,"NƠI KHỞI HÀNH không được trùng với ĐIỂM ĐẾN","LỖI");
           return;
        }
        try {
            TuyenBay KH=new TuyenBay();
            SanBayDao SB=new SanBayDao();
            TuyenBayDao dao= new TuyenBayDao();
            TuyenBay KH1=dao.findTuyenBay(s1, s2);
            if (KH1!=null) {
                 MessageHelper.ErrorMesage(this,"Chuyến Bay này ĐÃ TỒN TẠI","LỖI");
            }
            else
            {
            SanBay SB1=SB.FindTenSanBay(txt_noikhoihanh.getText());
            KH.setMaTuyenBay(txt_matuyenbay.getText());
            KH.setSanBayDi(txt_noikhoihanh.getText());
           // KH.setSDT(Integer.parseInt(txt_SDT.getText()));
            KH.setSanBayDen(txt_diemden.getText());
            KH.setChieudai(Integer.parseInt(txt_chieudai.getText()));
            KH.setMaSanBay(SB1.getMaSanBay());
            if (dao.Insert(KH)==true) // Lệnh Insert để lưu 
            {
                MessageHelper.showConfirmMesage(parentForm, "Đã Lưu", "Thông báo");
                loadData();
            }
            else {
                MessageHelper.ErrorMesage(parentForm, "Không Lưu Được", "Cảnh Báo");
            }
        }    
        } catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,e.getMessage(),"ERROR");
        }
                                                
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
         StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(txt_matuyenbay, sb, "Mã Khách Hàng Không Được Để Trống ");
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentForm, sb.toString(), "ERROR");
            return;
        }
        if (MessageHelper.showConfirmMesage(parentForm, "Bạn Có muốn Xóa không ","Thông Báo") 
                == JOptionPane.NO_OPTION)
        {
            return;
        }
        try {
              TuyenBay KH=new TuyenBay();
            SanBayDao SB=new SanBayDao();
            SanBay SB1=SB.FindTenSanBay(txt_noikhoihanh.getText());
            KH.setMaTuyenBay(txt_matuyenbay.getText());
            KH.setSanBayDi(txt_noikhoihanh.getText());
           // KH.setSDT(Integer.parseInt(txt_SDT.getText()));
            KH.setSanBayDen(txt_diemden.getText());
            KH.setChieudai(Integer.parseInt(txt_chieudai.getText()));
            KH.setMaSanBay(SB1.getMaSanBay());
            KH.setTrangThai(1);
            TuyenBayDao dao= new TuyenBayDao();
            if (dao.Update(KH)==true) 
            {
                MessageHelper.showConfirmMesage(parentForm, "Đã Xóa", "Thông báo");
                loadData();
            }
            else {
                MessageHelper.ErrorMesage(parentForm, "Không Xóa Được", "Cảnh Báo");
            }
            
        }catch (Exception e) {
             e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,e.getMessage(),"ERROR");
        }                                    
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(txt_matuyenbay, sb, "Mã Tuyến Bay không được để trống");
        DataValidator.validateEmpty(txt_noikhoihanh, sb, "Nơi Khởi Hành không được để trống");
        DataValidator.validateEmpty(txt_diemden, sb, "Điểm Đến không được để trống");
        DataValidator.validateEmpty(txt_chieudai, sb, "Chiều Dài không được để trống");
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentForm, sb.toString(), "ERROR");
            return;
        }
        try {
            TuyenBay KH=new TuyenBay();
            SanBayDao SB=new SanBayDao();
            SanBay SB1=SB.FindTenSanBay(txt_noikhoihanh.getText());
            KH.setMaTuyenBay(txt_matuyenbay.getText());
            KH.setSanBayDi(txt_noikhoihanh.getText());
           // KH.setSDT(Integer.parseInt(txt_SDT.getText()));
            KH.setSanBayDen(txt_diemden.getText());
            KH.setChieudai(Integer.parseInt(txt_chieudai.getText()));
            KH.setMaSanBay(SB1.getMaSanBay());
            KH.setTrangThai(0);
            TuyenBayDao dao= new TuyenBayDao();
            if (dao.Update(KH)==true) 
            {
                MessageHelper.showConfirmMesage(parentForm, "Đã Lưu", "Thông báo");
                loadData();
            }
            else {
                MessageHelper.ErrorMesage(parentForm, "Không Lưu Được", "Cảnh Báo");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,e.getMessage(),"ERROR");
        }
                      
    }//GEN-LAST:event_btn_updateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_layma;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_diemden;
    private javax.swing.JComboBox<String> cb_noikhoihanh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_tuyenbay;
    private javax.swing.JTextField txt_chieudai;
    private javax.swing.JTextField txt_diemden;
    private javax.swing.JTextField txt_matuyenbay;
    private javax.swing.JTextField txt_noikhoihanh;
    // End of variables declaration//GEN-END:variables
}
