/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.mAdmin;

import java.awt.BorderLayout;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import sang.ne.ql_mb.Dao.ChuyenBayDao;
import sang.ne.ql_mb.Dao.TuyenBayDao;
import sang.ne.ql_mb.entity.ChuyenBay;
import sang.ne.ql_mb.entity.TuyenBay;
import sang.ne.ql_mb.help.DataValidator;
import sang.ne.ql_mb.help.MessageHelper;

/**
 *
 * @author Yahiko
 */
public class Trip_Manager extends javax.swing.JPanel {
    private DefaultTableModel mdDefaultTableModel;
    private MainFrameAdmin parentForm; 
    private chitietform chitietform;
    private chitiet_ChuyenBay chitietChuyenBay;
    String[] arr=new String[100];
    int i=0;
    /**
     * Creates new form Trip_Manager
     */
    public Trip_Manager() {
        initComponents();
        initTable();
        LoadTable();
        cb_Tuyenbay.removeAllItems();
        try {
           
            TuyenBayDao tuyenbay = new TuyenBayDao();
            List< TuyenBay > list = tuyenbay.findalltuyenBay();
            for (TuyenBay cb : list){
               arr[i]=cb.getMaTuyenBay(); 
               i++;
               }             
         } catch (Exception e) {
         }
          for (int j = 0; j<i; j++) {
                    cb_Tuyenbay.addItem(arr[j]);
             }     
    }
     public void initTable(){
       mdDefaultTableModel = new DefaultTableModel();
       JScrollPane jsp=new JScrollPane();
       table_trip.add(jsp,BorderLayout.CENTER);
       mdDefaultTableModel.setColumnIdentifiers(new String[]{"Mã Chuyến Bay","Mã Tuyến Bay","Ngày Bay",
                                        "Thời Gian Bay"," Số Ghế ", "Mã Chi Tiết Chuyến Bay"});
       table_trip.setModel(mdDefaultTableModel); 
    }
     public void LoadTable(){
         try {
            ChuyenBayDao chuyenbay=new ChuyenBayDao();
            List < ChuyenBay > list=chuyenbay.findChuyenBay();
            mdDefaultTableModel.setRowCount(0);
           for(ChuyenBay sb :list)
               mdDefaultTableModel.addRow(new Object[]{
                   sb.getMaChuyenBay(),sb.getMaTuyenBay(),sb.getNgayGio(),sb.getThoiGianBay(),sb.getSoGheTrong(),
                   sb.getMaChiTietChuyenBay()});
           mdDefaultTableModel.fireTableDataChanged();
        } catch (Exception e) {
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_trip = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        machuyenbay = new javax.swing.JTextField();
        soghe = new javax.swing.JTextField();
        ngaybay = new javax.swing.JTextField();
        thoigianbay = new javax.swing.JTextField();
        machitiet = new javax.swing.JTextField();
        matuyenbay = new javax.swing.JTextField();
        btn_new = new javax.swing.JButton();
        btn_add = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_chitiet = new javax.swing.JButton();
        cb_Tuyenbay = new javax.swing.JComboBox<>();
        btn_layma = new javax.swing.JButton();
        btn_machitiet = new javax.swing.JButton();

        table_trip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        table_trip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_tripMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_trip);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/id_bill.png"))); // NOI18N
        jLabel1.setText("Mã Chuyến Bay");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/chair.png"))); // NOI18N
        jLabel2.setText("Số Ghế");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/date.png"))); // NOI18N
        jLabel3.setText("Ngày Bay");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/time.png"))); // NOI18N
        jLabel4.setText("Thời Gian Bay");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/details.png"))); // NOI18N
        jLabel5.setText("Mã Chi Tiết Chuyến Bay");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/id_bill.png"))); // NOI18N
        jLabel6.setText("Mã Tuyến Bay");

        matuyenbay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matuyenbayActionPerformed(evt);
            }
        });

        btn_new.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/new.png"))); // NOI18N
        btn_new.setText("Tạo Mới ");
        btn_new.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_newActionPerformed(evt);
            }
        });

        btn_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/add.png"))); // NOI18N
        btn_add.setText("Thêm");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/delete.png"))); // NOI18N
        btn_delete.setText("Xóa");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Account/edit.png"))); // NOI18N
        btn_update.setText("Cập Nhật");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_chitiet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/Flight/details.png"))); // NOI18N
        btn_chitiet.setText("Chi Tiết");
        btn_chitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chitietActionPerformed(evt);
            }
        });

        cb_Tuyenbay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_Tuyenbay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_TuyenbayActionPerformed(evt);
            }
        });

        btn_layma.setText("Lấy Mã");
        btn_layma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laymaActionPerformed(evt);
            }
        });

        btn_machitiet.setText("Chi Tiết");
        btn_machitiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_machitietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ngaybay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(thoigianbay, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(soghe, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                            .addComponent(machuyenbay)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                    .addComponent(btn_new, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_delete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(machitiet, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(matuyenbay))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btn_chitiet))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btn_layma)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn_update, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                                .addGap(85, 85, 85))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(277, 277, 277)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_machitiet)
                                    .addComponent(cb_Tuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(machuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_layma))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soghe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ngaybay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thoigianbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(machitiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btn_machitiet))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_Tuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matuyenbay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_chitiet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add)
                    .addComponent(btn_new))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_delete)
                    .addComponent(btn_update))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 503, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void matuyenbayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matuyenbayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matuyenbayActionPerformed

    private void table_tripMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tripMouseClicked
         try {
            int row=table_trip.getSelectedRow();
            if (row>=0) 
            {
                String id=(String) mdDefaultTableModel.getValueAt(row,0);
                ChuyenBayDao sb=new ChuyenBayDao();
                ChuyenBay chuyenb =sb.find1ChuyenBay(id);
                if (chuyenb!=null) {
                    machuyenbay.setText(chuyenb.getMaChuyenBay());
                    matuyenbay.setText(chuyenb.getMaTuyenBay());
                    machitiet.setText(chuyenb.getMaChiTietChuyenBay());
                    Format formatter = new SimpleDateFormat("yyyy-MM-dd");
                    String s = formatter.format(chuyenb.getNgayGio());
                    ngaybay.setText(s);
                   // Format formatt = new SimpleDateFormat("HH:mm:ss");
                    //String ss=formatt.format(chuyenb.getThoiGianBay());
                   // thoigianbay.setText(ss);
                   thoigianbay.setText(chuyenb.getThoiGianBay());
                    int tg=chuyenb.getSoGheTrong();
                    soghe.setText(String.valueOf(tg));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
             MessageHelper.ErrorMesage(parentForm,"Lỗi","Lỗi");
        }
    }//GEN-LAST:event_table_tripMouseClicked

    private void btn_newActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_newActionPerformed
        machitiet.setText("");
        machuyenbay.setText("");
        matuyenbay.setText("");
        ngaybay.setText("");
        thoigianbay.setText("");
        soghe.setText("");
        LoadTable();
    }//GEN-LAST:event_btn_newActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        StringBuilder sb=new StringBuilder();
        //DataValidator.validateEmpty(txt_TENKH, sb, "TENKH không được để trống");
        //DataValidator.validateEmpty(txt_SDT, sb, "SDT không được để trống");
       
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentForm, sb.toString(), "ERROR");
            return;
        }
        try {
            ChuyenBay CB=new ChuyenBay();
            CB.setMaChuyenBay(machuyenbay.getText());
            CB.setMaTuyenBay(matuyenbay.getText());
           // KH.setSDT(Integer.parseInt(txt_SDT.getText()));
            String s=ngaybay.getText();
            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(s);
            CB.setNgayGio(date1);
            CB.setThoiGianBay(thoigianbay.getText());
            CB.setMaChiTietChuyenBay(machitiet.getText());
            CB.setSoGheTrong(Integer.parseInt(soghe.getText()));
            ChuyenBayDao dao= new ChuyenBayDao();
            if (dao.Insert(CB)==true) // Lệnh Insert để lưu 
            {
                MessageHelper.showConfirmMesage(parentForm, "Đã Lưu", "Thông báo");
                LoadTable();
            }
            else {
                MessageHelper.ErrorMesage(parentForm, "Không Lưu Được", "Cảnh Báo");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,e.getMessage(),"ERROR");
        }
        
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
         StringBuilder sb=new StringBuilder();
        DataValidator.validateEmpty(machuyenbay, sb, "Mã Sân Bay Không Được Để Trống ");
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentForm, sb.toString(), "ERROR");
            return;
        }
        if (MessageHelper.showConfirmMesage(parentForm, "Bạn Có muốn Xóa không ","Thông Báo") 
                == JOptionPane.NO_OPTION)
        {
            return;
        }
        try {
            ChuyenBay CB=new ChuyenBay();
            CB.setMaChuyenBay(machuyenbay.getText());
            CB.setMaTuyenBay(matuyenbay.getText());
           // KH.setSDT(Integer.parseInt(txt_SDT.getText()));
            String s=ngaybay.getText();
            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(s);
            CB.setNgayGio(date1);
            CB.setThoiGianBay(thoigianbay.getText());
            CB.setMaChiTietChuyenBay(machitiet.getText());
            CB.setSoGheTrong(Integer.parseInt(soghe.getText()));
            CB.setTrangThai(1);
            ChuyenBayDao dao= new ChuyenBayDao();
            if (dao.Update(CB)==true) // Lệnh Insert để lưu 
            {
                MessageHelper.showConfirmMesage(parentForm, "Đã Xóa", "Thông báo");
                LoadTable();
            }
            else {
                MessageHelper.ErrorMesage(parentForm, "Không Xóa Được", "Cảnh Báo");
            }
            
        }catch (Exception e) {
             e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,e.getMessage(),"ERROR");
        }                                       
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        StringBuilder sb=new StringBuilder();
        //DataValidator.validateEmpty(txt_TENKH, sb, "TENKH không được để trống");
        //DataValidator.validateEmpty(txt_SDT, sb, "SDT không được để trống");
       
        if (sb.length()>0) {
            MessageHelper.ErrorMesage(parentForm, sb.toString(), "ERROR");
            return;
        }
        try {
            ChuyenBay CB=new ChuyenBay();
            CB.setMaChuyenBay(machuyenbay.getText());
            CB.setMaTuyenBay(matuyenbay.getText());
           // KH.setSDT(Integer.parseInt(txt_SDT.getText()));
            String s=ngaybay.getText();
            Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(s);
            CB.setNgayGio(date1);
            CB.setThoiGianBay(thoigianbay.getText());
            CB.setMaChiTietChuyenBay(machitiet.getText());
            CB.setSoGheTrong(Integer.parseInt(soghe.getText()));
            CB.setTrangThai(0);
            ChuyenBayDao dao= new ChuyenBayDao();
            if (dao.Update(CB)==true) // Lệnh Insert để lưu 
            {
                MessageHelper.showConfirmMesage(parentForm, "Đã Lưu", "Thông báo");
                LoadTable();
            }
            else {
                MessageHelper.ErrorMesage(parentForm, "Không Lưu Được", "Cảnh Báo");
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            MessageHelper.ErrorMesage(parentForm,e.getMessage(),"ERROR");
        }
         
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_chitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chitietActionPerformed
        String ma=matuyenbay.getText().toString();
        chitietform=new chitietform(ma);
       chitietform.setVisible(true);
    }//GEN-LAST:event_btn_chitietActionPerformed

    private void cb_TuyenbayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_TuyenbayActionPerformed
        if (cb_Tuyenbay.getSelectedItem()!=null) {
            matuyenbay.setText(cb_Tuyenbay.getSelectedItem().toString());
        }
        else 
            matuyenbay.setText(cb_Tuyenbay.getItemAt(1));
    }//GEN-LAST:event_cb_TuyenbayActionPerformed

    private void btn_laymaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laymaActionPerformed
        try {
            String giatri;
            ChuyenBayDao tb=new ChuyenBayDao();
            Random random=new Random();
            do 
            {
                giatri="";
                int value=random.nextInt(100)+ 1;
                if (value<10)
                {
                    giatri="VN0"+ String.valueOf(value);
                }  
                else
                {
                    giatri="VN"+ String.valueOf(value);
                }       
            }   while(tb.find1ChuyenBay(giatri)!=null) ;
            machuyenbay.setText(giatri);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_laymaActionPerformed

    private void btn_machitietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_machitietActionPerformed
        chitietChuyenBay=new chitiet_ChuyenBay();
        chitietChuyenBay.setVisible(true);
    }//GEN-LAST:event_btn_machitietActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_chitiet;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_layma;
    private javax.swing.JButton btn_machitiet;
    private javax.swing.JButton btn_new;
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_Tuyenbay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField machitiet;
    private javax.swing.JTextField machuyenbay;
    private javax.swing.JTextField matuyenbay;
    private javax.swing.JTextField ngaybay;
    private javax.swing.JTextField soghe;
    private javax.swing.JTable table_trip;
    private javax.swing.JTextField thoigianbay;
    // End of variables declaration//GEN-END:variables
}
