/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sang.ne.ql_mb.ui.mUser;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import sang.ne.ql_mb.Dao.KhachHangDao;
import sang.ne.ql_mb.entity.KhachHang;
import sang.ne.ql_mb.mMainFrame.Login;

/**
 *
 * @author CCLaptop.com
 */
public class MainUser extends javax.swing.JFrame {

    private Login mLogin;
    private weForm weform;
    private hosoForm mhosoForm;
    KhachHang kh =new KhachHang();
    KhachHangDao dao= new KhachHangDao();
    private MyTicket mMyTicket;
    private sang.ne.ql_mb.mAdmin.Home home;
    int index=0;
    private AboutUs mAboutUs;
    private appInfo mappInfo;
    String Username;
    /**
     * Creates new form MainUser
     */
    public MainUser() {
        initComponents();
        home();
    }
    
    public MainUser(String Username) throws Exception{
        initComponents();
        setLocationRelativeTo(null);
        kh=dao.FindUserName(Username);
        this.Username = Username;
        setTitle("");
        home();
    }
    public void home(){
        home=new sang.ne.ql_mb.mAdmin.Home();
        tbl_mainUser.addTab("Trang Chủ", home);
        tbl_mainUser.setSelectedComponent(home);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator7 = new javax.swing.JSeparator();
        jToolBar1 = new javax.swing.JToolBar();
        logoutBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btn_home = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        datveBtn = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        ticketBtn = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        hosoBtn = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        tbl_mainUser = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        DatVeBtn = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        appInfoBtn = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        aboutUsBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setBackground(new java.awt.Color(0, 204, 204));
        jToolBar1.setForeground(new java.awt.Color(255, 153, 153));
        jToolBar1.setRollover(true);

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/exit48.png"))); // NOI18N
        logoutBtn.setText("Thoát");
        logoutBtn.setFocusable(false);
        logoutBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logoutBtn.setMaximumSize(new java.awt.Dimension(90, 85));
        logoutBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(logoutBtn);
        jToolBar1.add(jSeparator3);

        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/home48.png"))); // NOI18N
        btn_home.setText("Trang Chủ");
        btn_home.setFocusable(false);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_home.setMaximumSize(new java.awt.Dimension(90, 85));
        btn_home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_home);
        jToolBar1.add(jSeparator4);

        datveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/plane48.png"))); // NOI18N
        datveBtn.setText("Đặt Vé");
        datveBtn.setFocusable(false);
        datveBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        datveBtn.setMaximumSize(new java.awt.Dimension(90, 85));
        datveBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        datveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datveBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(datveBtn);
        jToolBar1.add(jSeparator5);

        ticketBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/ticker48.png"))); // NOI18N
        ticketBtn.setText("Vé Của Tôi");
        ticketBtn.setFocusable(false);
        ticketBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ticketBtn.setMaximumSize(new java.awt.Dimension(90, 85));
        ticketBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ticketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(ticketBtn);
        jToolBar1.add(jSeparator6);

        hosoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/man48.png"))); // NOI18N
        hosoBtn.setText("Hồ Sơ");
        hosoBtn.setFocusable(false);
        hosoBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hosoBtn.setMaximumSize(new java.awt.Dimension(90, 85));
        hosoBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        hosoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hosoBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(hosoBtn);
        jToolBar1.add(jSeparator8);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/Logo48.png"))); // NOI18N
        jToolBar1.add(jLabel1);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/configuration-gears.png"))); // NOI18N
        jMenu1.setText("Hệ Thống");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/exit (1).png"))); // NOI18N
        jMenuItem1.setText("Đăng Xuất");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator2);

        jMenuBar1.add(jMenu1);

        DatVeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/plane-ticket.png"))); // NOI18N
        DatVeBtn.setText("Đặt Vé");
        DatVeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatVeBtnActionPerformed(evt);
            }
        });

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/plane-ticket.png"))); // NOI18N
        jMenuItem2.setText("Đặt Vé");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        DatVeBtn.add(jMenuItem2);

        jMenuBar1.add(DatVeBtn);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/question.png"))); // NOI18N
        jMenu3.setText("Trợ Giúp");

        appInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/information.png"))); // NOI18N
        appInfoBtn.setText("Về Ứng Dụng");
        appInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appInfoBtnActionPerformed(evt);
            }
        });
        jMenu3.add(appInfoBtn);
        jMenu3.add(jSeparator1);

        aboutUsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/group.png"))); // NOI18N
        aboutUsBtn.setText("About Us");
        aboutUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsBtnActionPerformed(evt);
            }
        });
        jMenu3.add(aboutUsBtn);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
            .addComponent(tbl_mainUser)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbl_mainUser, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mLogin=new Login(this, rootPaneCheckingEnabled);
        mLogin.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void aboutUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsBtnActionPerformed
        // TODO add your handling code here:
        mAboutUs = new AboutUs();
        mAboutUs.setVisible(true);
    }//GEN-LAST:event_aboutUsBtnActionPerformed

    private void ticketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketBtnActionPerformed
        // TODO add your handling code here:
        
        mMyTicket =new MyTicket(kh);
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/ticker32.png"));
        tbl_mainUser.addTab("Vé Của Tôi",icon,mMyTicket,"Vé Của Tôi");
        tbl_mainUser.remove(index);
        //tbl_Mainboard.addTab("Quản Lý Khách Hàng", mCustomer_Manager);
        tbl_mainUser.setComponentAt(index ,mMyTicket);
        tbl_mainUser.setSelectedComponent(mMyTicket);
    }//GEN-LAST:event_ticketBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        mLogin=new Login(this, rootPaneCheckingEnabled);
        mLogin.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void hosoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hosoBtnActionPerformed
        // TODO add your handling code here:
        mhosoForm =new hosoForm(kh);
        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/man32.png"));
        tbl_mainUser.addTab("Hồ Sơ",icon,mhosoForm,"Hồ Sơ");
        tbl_mainUser.remove(index);
        tbl_mainUser.setComponentAt(index , mhosoForm);
        tbl_mainUser.setSelectedComponent(mhosoForm);
    }//GEN-LAST:event_hosoBtnActionPerformed

    private void datveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datveBtnActionPerformed
        // TODO add your handling code here:
      
        try {
           weform = new weForm (kh); 
        } catch (Exception e) {
        }

        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/plane32.png"));
        tbl_mainUser.addTab("Đặt Vé",icon,weform,"Đặt Vé");
        tbl_mainUser.remove(index);
        tbl_mainUser.setComponentAt(index , weform);
        tbl_mainUser.setSelectedComponent(weform);
    }//GEN-LAST:event_datveBtnActionPerformed

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        try {
            this.dispose();
            MainUser main=new MainUser(Username);
            main.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(MainUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_homeActionPerformed

    private void appInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appInfoBtnActionPerformed
        // TODO add your handling code here:
        mappInfo = new appInfo();
        mappInfo.setVisible(true);
    }//GEN-LAST:event_appInfoBtnActionPerformed

    private void DatVeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatVeBtnActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_DatVeBtnActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        try {
           weform = new weForm (kh); 
        } catch (Exception e) {
        }

        ImageIcon icon =new ImageIcon(getClass().getResource("/sang/ne/ql_mb/icon/IMG/ticker32.png"));
        tbl_mainUser.addTab("Đặt Vé",icon,weform,"Đặt Vé");
        tbl_mainUser.remove(index);
        tbl_mainUser.setComponentAt(index , weform);
        tbl_mainUser.setSelectedComponent(weform);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu DatVeBtn;
    private javax.swing.JMenuItem aboutUsBtn;
    private javax.swing.JMenuItem appInfoBtn;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton datveBtn;
    private javax.swing.JButton hosoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTabbedPane tbl_mainUser;
    private javax.swing.JButton ticketBtn;
    // End of variables declaration//GEN-END:variables
}
